apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amrelabbasy11/Sealedsecrets-Auto-Reencrypt.git'
    targetRevision: HEAD
    path: sealedsecrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
