---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-2
  namespace: default
spec:
  encryptedData:
    apiKey: AgAu7A4YYMCx9vyAiBK6mcHKKsKYjlQ1tsEEAFI+kN19NE4Dx1uguxxHhFYlHnLxQYqptcVfoooIpGPAbWt/ecNfg6tnA1WyC9/VJFwp2MhK5llKHLxGfdeQYKhZdSI15gADf1rsmmAz/PxBujZAg8fOqUod7+ipGh/EJMxfW6R7qm7lN+ZjHhQEWpIFXxkQh8UOM+Zq8Kcn+foUPwTyvXGq4ZiDE3MuMFhMqHge9nTCMhj3MZ923G7Sh/opKQRRfVDfx+78iOjdbo/ccFAf93MTr5Cqq3E2iFS7egr0fAGg0gfaeZMidqFqIAdEqPIj4zc9gk5HrwCHc0g9+bXt12IhLKb4nGPmCDd6NZYvhcGN9mx4bJv8h56n+Im818xH9qmh6KRCksg2vjQ0V1qOpwT6NQOwGvxxJgwAVja2Cj14d9T4ThZNlPIDWsr6guITJ/QFBqZSJGJe955xzHtjMK9VPDP0abJffE7IcuZD0QaYhVTbMZ2jjQzFCW8BVJtxFIuP+fs0EC2h/dIMGVPWTwdt644JTm+nfofSSA/sViPwr8fNOPsJn17bzOstEJXpCVnEa7kLzlsUlDpjI1MAqkPVuWtToQ4u97qEpUQZphi3zQ6g8DVRVXDwkn/ZMG83aRnRLtWo1tnFVIsTfZI7wTc0T/GphECNMXeueLwI0o5qlrL51ERri1QYxdPezDRkkvl9qgREhkex4R8=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-2
      namespace: default
    type: Opaque
