---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-2
  namespace: default
spec:
  encryptedData:
    apiKey: AgCz7sMJNH/h6Bc6ublmgs1wF2Fx/aWhvc7nMoYubR/VeKse7x2YRAkhfu5KZwpdY7+xMIMeWCYIoPASoELJzIpqZWOvCy7SDgywJM23u/y3SDvoRSkIdAT9GOaEOXds0t188AtPf4BVga43jvONfKRkWYbQd4B7RVAD1G6DcFKlRAssvc6kQI/D/hxI+KR0rdgwy4WQepU+a3SxAjTmSGIYtUxO3F33DXLOdvRXrOQwqsGUk4VpiKSzVKq461sndGgz7S2B/4B+bK+rhLV+LK7/5e3exdFCBmuyEi/vm2qDqp40PulvYjclhgt83cWtdOFCVYTxuFaOGw3OFos41ra0nodEshictzzWRACisiOpDpBHtUrE3N2yybpF4MXkzztXOgmV9tq7pyhrK5oam7UlIohNXNcZKI18/zs96hT3ADT6u3QzRRmyG905szHu3S7BqJB74flpxQw7FDrxvVF8XipO3GlcMh+fb08Txu52tfoSJRtMHwKTK2rvF9U9/SMOzsqE8OlsY/nIDVgS9X7SpPWUY/G9JHkXM01quLtOeA/XLGxvrdgiwskcEwjlr4cKAKh95Hz4ZGY2aJb1DRbXUsYazyMWWwdCkoJXPZMOBLw6du/RJjVLWrNDVio4Ofr+FGO+Es4lrPrh3aGa6w7W29801jlTfcg/93PY+zPqFCMPcyosorofaFfe/6pSVOWmvJpgLC/ySVw=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-2
      namespace: default
    type: Opaque
