---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgAun15EUEB35N2XA1VkAD8+y90HLTxdBFTjuVo9tWx+twcinc/im/w+q+HSy7ebJzyyOo1bxVMAMQn1obMwaXX8JaGTMe3jDl4PbIKmLlht29alJSJ0ZC8O8V6MsrafflA/ZteesIzp+HQ9g1l5qZbQvJSlZgKYC+INY3QkCuq8SFAzkDVJwMom5AN44dbbOA7qqsesAEXeUR+6i1jdDqbN0ASrZK6WElXX/BXvwrfsfc0VCUhdfDWwPOBS6MEFDMKg4Sbd8UBxD57M2Q1K47I9XEhpZ/cKnW0yZGKBwkwsJzpArXDLL4pK77NTovcHBZirNc4ObsfVUm0dC0DCLNLg7NkQghaDZNZPR2spC0Xg9+JGn6DvDVpLmTwczmr7PFjVMvMDyT4xyPSnhKq+jJKZi+KN5xiAc1yuMnpYX5tT0CwUsaleNhg+k+uDKxLdgKc10pDudKjL8ntfzk+drrXUbIATXMvJWLu0gt5EkbBtuTZAWNqPRGym+mKoZsz1L5O3pWZbTthNlDzchS0b0r83C7Lml63OVyist2xMxjbNS9auISKFNszDLcdsqP16cPmXe56xLS0YjEa+2NHVM+9o0zwgv2sSDsr3+P68Xe74nDGGwJhfSD2eSFHE4CwJfRYH8/IIZTHpn3D+qr3Kh7bhOEDwOwAGqqAVkTkvQARj6zto9r9hOEVVneQWJobD+oF8rhyw4h7h92xzpk0Wrjy1+rqn
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
