---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgBzXHbdGW5/9UdmJqQz9v0uH5SASr+pTE6g9lqEPgdDijX/4EQddBkvVtrnIR3YX6PssvWx5iB7OsczxfnRMGgUB4zlRbm3RXxC4RBQfEKJUR6TX7BgYU+0oKNDrSEWBI0928yBVk2/mGncFdjWFPKIwM3EIfKSuyRoG7ZGVJ8T14s8eFtf/SAGJLt7t4gAiV1Z5GkPT4xPW/aKpNryEJHRkaq1Hp0KDRn3lOY6Mz2w+LpxdjPzhkzdy9ukjNJOObFhMCSc7aVYzEdhQeiQPO327chx/86icv0eq2o6xEcQ19K/ZEEc+XToROWb8LalGbj2NHJsGdaob6FUQs28Jn9qdShUneW3a530D14Yp2SKDM4WnI0j0oQLzrTD2tkPKcqhpVMJTkRN60hNwdrEWmYR9Igz3FAOuXu4ORjcEM0fpu6zGPBJJQ5MnatXqc4tDaZfkL5dIpa9l0MgPV1VQ7jA9f2cxQY8/ms52GiOfmiiSKUsDSqIsHCwQzLc6IwqRd561v5ORM+QOXuPqV3CpS1B62Fk/XHl+i3+tmdQio/dvt7KD4D7d0Po5Nw5vjJaEgpoZ6Xx/7OO02cQ4oJqGjiXqZ1xU64TNjoePjM5kgLdoKJ/0Pjh/qOdhJETBFqR3WZ27oGfJGbRLfaVZKHwl6qq++nheBihjFqy+B65+YD0h3qQien85PBF75GJDATAcBaV/HxLHgF8xv5TRyNIeDoACZDk
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
