---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgAbM5J+WI8j1YbVEexo7oQtMh1E0aTu1qnCJQgPgsd6JzhTBIYZaYtRRgdBWlQtrTLpsmh1/iwdBcqu4lmfnEQmQlZNiOU4yvTv5A6e6TzH4YoYm5FpSOvU1jns4rfEr4oPrYp0FIqssB/mzpdww4OACKSuEdoGUEyszGz/jEefzUjy1RbJIhJI/jJh5ohGWioHOLs6ValDEiC8GwLioY5Bojo0ojRZt152b9+gqbm3OjnB+EyMogZjhCyU8nEObukaCDVrsNgDAEqu5u8l/bmM+9iXmBsppqH4jZvx/UD5o/1yRwuiBL1rUuaWTWU0l0hYoXwLJLI4ErhEHLS8Dc2a/ODVPXn75NL6h4U+jrxV/exRnnEKnHI1JK68t4sGnhbH4+w/2Cnju20NaI6sYTuXivUPqxinHLpoJX4qzgblnCojmST8FqVS7Mpi0ntcAJ1qJFjKJyHcjh9BE/yyVwD6o21IlBRlENOZELfP5HBYv6VKhxupfEzWnkyxDJJyL2K5kLG+BcwDG5w6iHHZX6k6i09wrfrpBoxkdk9n0JosWFKTrytMU0+JSvjrer+JunIYFKYrzFcD/0ypN5ktgrc+Hvtbu6h59KwZcn5kUk/32B6qeCfbkkqH1nIxuMkBF1gRIzn8aYeKTibWr7D7wIJ+yHjLTJc4d36ZV+y9d8tcGR31EfFyWhlFW1a3UMKv5u4NKAZBn+54koPsidK6rdDNZ9NL
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
