---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgCnt3nysZlP075cvwd7zhevNjTyq21+A8j+GmPwmgx/1cF5dRu7j+dHI76IkPPz+ey4HzWfkXHCSRMTPHkFoBSssh6pq/92zIYneRcCu1f98XUeweSgRn0fgCI7XG7V/Nvgl3eL4kuHPhxh7auXfNDrUNNs5BrURAgU48Th4TnpKFuGVT2m1lPU0TJXXVcT0Ib/vJdXWeUW3jihRQq2QKAIoAVRPuwe7klzvt2y2/XfVBdqILF7fdeTsJxCNcJWYjH/peHp2faDTkkjPJK1lJQJ7p0kqlQ1OeEDEXlGjYBNRQ1dcVK2Ee07U/WPJaUHKGF35zqzssFDmJliCLLZJAIfEJ2EXiEto9zZQq1TDVwNw4rUZjMx9+gmoteQEtdg9spO3f/vX5SVNSnd+IQ9B+sEPW/XlUxsQBQubxeY6R4QY3hsOOS+aix9/I9U6uFtpVNoHR3tnX06PHaJwfWabdlUsT3jSpFTO7Yurqc7egZ8GLir5XQARF1614RKdZaI3BE5JJa1rcwoJtY7icAKhmWZcW7rCimQgbdaz7LZFM//JBSGc0by5RGO+n3znp4/RqUnZmPf9xgLM2YVp5qXx6YY0eoKSR/rnvJvp9FnFHGZfG2teIe0nSyThVh+EH/QhP50L9Wpqo58ITfj1sbm3xjkeMlgOkT2YRZ4M1XYPALNyfd0a6r5Y4m+zUeeEMfH0+GGtD+is/RTz/PShVR4ik//dWt6
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
