---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgBzGONII2D0JSjphX17v8lQhEG7lwQVHW/tVjIxcs/BNvQ1jpoGDlw9CVk8X4dRoayPtowmp0Wu6KpmWfiLunj9047HXlFv0nJoDsvgVQA/5VDqNQ/HMTUJkmxFwy1klrG2iM5kiYVyse8FivXxavY8BYWZIZ8MtYJozQGL3kI9k1GwAbykT3RGx89lB/ZC++buW1BVIZK0Yv1B6SNBNUZAqGoI+TQmiJ1cw1yIYS3osyu+vbi/aOUh7QfXyQcaAf7ht0+lEszWT5qexz2Doyg73ZkrOKZm9sk1kbUtbAEnPn4oGHrzRay/HTNveD3NWyaZMuVTBeVJ7X5jcK4tzgkrRI6k//kiMuhhP5Kc1CvyafDLbyqHXKRmOUpR7VlsvTAjr/t/Oo/pMn8liJkDvZJLK969okqzEKoNmt7+NT8GjBGCZGZ5OSxwR3caYVhtrUICVADbb6uljQD+a6u9KPpcdKV8mQbSTHw4oj/vwieD+Qc223qRBSdzQeMvdVN+QssLUjV4nr/pgSaZI9MpgnxmXfwF2DTnIvQ9xMhqR8RqAIbEjnS46Wkn23cMOagPYkf6R/xYKAbBa+ksiPKh3k6YrgQAJXP1dNV1COYfGys/HXXroFbYX+XKQOh0pm5fXgpYMOrD3HOLVQw2nQVIPOVow2Tgd8baTQw8Fyzpnv3or5jxBCHHbpGAxENvwEpLYJma6Uzz8fqrzo3VinUwxp8MNa9P
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
