---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgB2T7qFejTQWDlpjSlZ2BROojmoSNi+mV2alBhDWv6loHpUD23ilhNoACLAubFH3pPJOkGi2t9tc7tFCG1/ST/51S0VocCnxBSi8vWDF2lQhAnIYM2WfkwSve40TtPd3MEaQkmH5x4ktCx1JjmyW8++S2iMwnCc9WI+F4bYsAOeDWEzSPdF8BCPtc2LNyFeSypTHrARHoVoPyCoHstyg+um6lazCw0TXTwp8U2kkOcydN9oQXnj1rMvLElTY1gn7LMyWsm57cVW4TFWBY4v+qPsPByGy7m1fR+jJ6JMfn86lfXo2Oi9yuDmY8afYGlBmV60Ynq/ATd2+oYEZYaHDykP7RyNatybgjwWQU9VY7NsYm9HZMz1zA8mDaggFm+HlguKnwOmfy3kBOBeuZEwMKniSgpLq1uLQu+lx9ok9Q6NZ4eBI7h1A2Fd6gK70vD5itvZScDJGpsfZrc0BiJYEtUnCRrl/ZcflHbZs5oVU1VyoHJR7zbbtiRzsIt5r21P2W7XVD10X0kmZjEelOVZbh+YKDEbiZO+/vqrwPZ0Zq2s37U3bzBXDR3Lih6VCG/571A0Dw/Fthc2URDlnssvXoz1LJ1zL3LLjWPvMfbcLcuYlrLUE3KIUIuATKB1U4gF504W2AjtLZ7UjttkS1SD/YE8JdmT9ZQ1sZ4DylIPDlM7AdgafuB1CPts42g0Rvb9NfTPVY8NswpMh+H+NJqfv9PXl3GV
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
