---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-2
  namespace: default
spec:
  encryptedData:
    apiKey: AgChgGqzJ79ZQ7iQ5QYlgfE5I9UzpDf4ttSNYaGmInWDi4jeH1Ae1m49leLQKtvLn0/k9KbrEV9mPrxV2mksBKmpPD/MUlUg6njYOUJtZF7Xyys8wAeRcFKeKmhB+N+5qmaZKnElZdeze90UvafsMfESjKRPgEn4i62SpK3Lkz7K5xOcfWAPsGeGdCEPsbEyGxEfTYyhKoIUMy9BhTyHmu59TYzwFQ+rDHNccluG844KnSH85Fc+QK5kZE795PKA9VbziAMnHRLJFhti1Si4MvcAZtX75nrbqpMS8/xCerDXr5pi5TvI73FtA5KbvQVOWnz9C+RK6mHb+z53+AEKqQtQr4XC8AqR+HOZnm3b8C0z9rMUcPqXJxu1i17qY6mHvPrMYo0JEtrXvj7H1MUFqy0KtMIeuvoiPN6BghdSoNEjOaYsR8flr1ToVGC9sSl+VHNRToyAAkPAE7/DkoMlP6NXtT7q23iIkkUK8jRDD8Pm+fWQubUf7hfmBmIrnR+jLusWEB08yUKC0MbUOjsV1F4P0XBJ2Oa6GF6+8wNDVl4qQPKIEsqtR6aEOUi6lZ5rXew0HlDuXWs6E2QIaZcOjg5icy2DoK5IrB4VyY+dstzoC4qpJxiHIJJ1oBWTL+mjqP+ULUMU6t1IkWImAoB6GKLQ+FsRwfjx/pxcJw4P5J1HKDu09swRwiMKSl38yZRhx43SyNAfuDvBM7I=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-2
      namespace: default
    type: Opaque
