---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-2
  namespace: default
spec:
  encryptedData:
    apiKey: AgC77guVQPAY1WPAHbv21gGsqEGFZgv5vTb4qQQ1/tpe/LRz2Kn/gVUzjIE3USoyQmhCyXja+0PoMhaSBgzmot6lA6UfmKjxMQvvPNhHtndaiescIo7Dx1JYRCkmhhdsC1KN+OYP/zcpsnAJvlNuVQz1kDBgF9rKZHq7zGkL2FBkyM/06+iEhTTTUYGWdrPfSCxQR5Vec7GlT6O2KDHuPacIP9ZQMDxoYetaPkOiwOqsH2vPCEw7uku+2qFkJiu+yeXYhodyxeOUkCbYGxmZRTg8X5qODDf7X8trNCPVT/yNubXDO0K2PoYpkBSyP6LA+IsExd1A7usCcT+QSFZo76JRnkv3wZ3KSgqkxvh3cHh+JP7lbWCAsppXvq+pMBhSpKKtGPwEEka/7UNsfxJdngzpMrxXvAJdrrit46nyJYsJ1LMM+TjmyfZwzju1fq9mdnrifwe/GWgDrekrLtqL1etxhc24jjp6Ek/y3NOWtncazxv9nqrJGinXEk/1X0eCnamTaI2hz+OHWLK0I9BPqSZINJ2iT5RiUveVz8oEzri8SNm1rP8OlsvRjPUuiHDGCmoV69RLM8D2PRQ6BvarHb/9wf7v90HqNwFwlr4BYpEG3LcCGIZPsEeeUhsmY8lDuNwHVDDo32XCrYts4jzOvgqabs2EwyOa4psqDgVXQ1ixMFkkS6IHGctZ9WN+57jRqfJy09tzJhOrUJM=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-2
      namespace: default
    type: Opaque
