---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-2
  namespace: default
spec:
  encryptedData:
    apiKey: AgC7nFSiwAzmgfcN0nTveiTmDzosHEdlQ8ddrwA3WMPdZDipNZMolNu9smbTnznfsfp0k0Hss/cG+46tdx/VZYtvHuRA1czJUSReXXpKI092m+DEGFJMfsqbGJOl2GA2w0wmg0ZtZgVcbIuWaXFRDp1jURde6aBHDuEWFRyF5/UPi5pkR/Ohc4rn7VH2f98MMO+eHMiLm8O5qCKi9BCgLqOwn7Mq01WwxKCc1VTfcjPFj2GXFjwnYk3o/GJwC2aBp7fYQeu75on/geseE/YZ8LMDhDGMznBiMMgNv/h5jao9JuUxiuy368pYv8XF7+6veAsd8HLQgCshSilQdNWK716DqG7lUSD8KbKkMk/UTxOGpCvssoegRay2unr5V10Mme24G8BEiEl6zSH1TOvsYAcqDn9JmAVusl9h1MHCN4Q7FJdVHjbZOIrHtFnPS05hxXJVlgaNwHgXjbHZI/JJ3H11Akwkp5gYjLXAjffez2k4CybqQ9URQ6RTEhJy7i9JSlaPnc8cvPnaVX4wI3jcVH9zlgSb7rkVDXtermRICPXhblDKIwzqpZBtmiP87fhOg8KFknpuStpRHMBXCetGs+KzzbdQk4ZxQk1DLw5tznBD++MsjDbe+XAQNdKjt+/5x0ezqt+YLw2sCpCI2j20eTAiCmc8sKkK09LAosFbniDmfxM0vSQJHO7U9Y5c0ul9pBwsDcVIcFdn3Xc=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-2
      namespace: default
    type: Opaque
