---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgA4dKByZiEVf9Za76+o23cmUc0nufuqMzn4MM0JAPB9qFaimDzWTKyO+nTvfFN/qEveAXat1iOGVmksPAfWXLEkRWP4zEDNaeR1ttnEWp4XCe9wcEyN4IP6X/jZSCA6wniBhyeLcWi/Qi4+OljrAfaQRpW8p5Q15blQ9wElRlzIbF6W6hDU6MRBRsUSmM+TURaEDoU7YyEq+LpWEY2K9cvz81EBwkuNipuyV5xCqR6JdhT6IrQP4Zc4USL3KqpPrQn1JLzwOoYUHTI4FG2uo+y4iaGhNk+pYs7XmDs6aqwMTCPjtIvxsI1zMzgCD0EesuWu9z4clljqvfWMqtVLMWhNfXepDJWb0nPLRK1T/F36fhdAgu0w2mABZxkxlF0e3N+EWtMlOHG3Ti9JikgikYhGIC07B1JQ5zG0szXKYUw3qesdEgbfSMl+wBMjSwmq5ktxluQenz5BzB/jvuW3UGSDJyyYnNH5mQrZgiQefodwbV0TYsCkqAnN07gIWULQyqGikvJ/ghAVDP4+jH1yEnwoygB+oGURi0hK9dXHEuJQ4dOjttqAU8x/lW6Qm4/cAbn7pv6pcB0KIUO7i1GKhiJQd9YtTrr+Gb2HyLlORkaS4uiaYwLbM5VJL/Hi1ABjz80CRcSK4/1L/w0/uSnukSRYcKf/YalvKJR+ISuDj2ghkI5dSgKndSujzyB4mcyr5tUKYwpUBzNl0Rbv61JYtQxuZzR1
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
    type: Opaque
