---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret-1
  namespace: default
spec:
  encryptedData:
    password: AgDFy1b7QBli0echRGgLuL9LTDhQAuaGjUUV0dYoN+lYFM/XgMrJxSfgqa/RNiNo2aOx8GesOXP1AMAJ0KRzXhDe/JClFFORnuFTTx0B5RHrE1uoCiVbMEgQz9LERV+m3wCP/JSR8evZSfKq8szaIc5kS0SOpWVSZNVM/skbPvAJLIiI7Xl0rFWxWzndQQZy2JpOK1+7kIfhPCzFqCRYHyIiGgpYfyopNbaZWtVUBz261sPW3xn3IQ22eBgHgCAvDNP/V+/bIsV0KbpE/Sra3dHwBOmuo3k2MAC8jIngTKe1P26Mz5HW3L9ADyvj3ecHGc47vtCEP4OpDNVmHZSWHXOLDgt/OrBZoeRkNSB7LhCX0dNe8zEQ0Q/vf6ZjJjlJU0cpo3SOjUapRa5baGevJ4sPH6I7AdmttTMCfmox4b9gAJEYke63By9vOGf/7w/qznHQ6AD9BlwHbVtKbfjR62f4aHWhL18maM1cdwtMq4sUFZ7MWaceo5gtBFZA3qv/RFkPEaTaxFaM3Pta6ubRQN8PLWUiySk3Qbc4Q+AE01TYe0wj54vW3U+XjIuv3vUlsuMCzSY88ea+bsZGA/I8BQm4zUXPM8jmUYDvrstfVtR4VI6NtX9m04kWmuwsF6lQjv8o8MN9hYblwjrbwOQOkOSlpCYUB84gjNlEK+pjjLQGhUvQJ9tMF0aEly5Vlro7U3O3HYzPRhN8dDw6DpPusJQORnuS
  template:
    metadata:
      creationTimestamp: null
      name: my-secret-1
      namespace: default
